//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SaoVietStoring.Entites
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StoringSystemEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StoringSystemEntities object using the connection string found in the 'StoringSystemEntities' section of the application configuration file.
        /// </summary>
        public StoringSystemEntities() : base("name=StoringSystemEntities", "StoringSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StoringSystemEntities object.
        /// </summary>
        public StoringSystemEntities(string connectionString) : base(connectionString, "StoringSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StoringSystemEntities object.
        /// </summary>
        public StoringSystemEntities(EntityConnection connection) : base(connection, "StoringSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Account> Accounts
        {
            get
            {
                if ((_Accounts == null))
                {
                    _Accounts = base.CreateObjectSet<Account>("Accounts");
                }
                return _Accounts;
            }
        }
        private ObjectSet<Account> _Accounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MailAddressReceiveMessage> MailAddressReceiveMessages
        {
            get
            {
                if ((_MailAddressReceiveMessages == null))
                {
                    _MailAddressReceiveMessages = base.CreateObjectSet<MailAddressReceiveMessage>("MailAddressReceiveMessages");
                }
                return _MailAddressReceiveMessages;
            }
        }
        private ObjectSet<MailAddressReceiveMessage> _MailAddressReceiveMessages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Storing> Storings
        {
            get
            {
                if ((_Storings == null))
                {
                    _Storings = base.CreateObjectSet<Storing>("Storings");
                }
                return _Storings;
            }
        }
        private ObjectSet<Storing> _Storings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccounts(Account account)
        {
            base.AddObject("Accounts", account);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MailAddressReceiveMessages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMailAddressReceiveMessages(MailAddressReceiveMessage mailAddressReceiveMessage)
        {
            base.AddObject("MailAddressReceiveMessages", mailAddressReceiveMessage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Storings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStorings(Storing storing)
        {
            base.AddObject("Storings", storing);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoringSystemModel", Name="Account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Account CreateAccount(global::System.Int32 id)
        {
            Account account = new Account();
            account.Id = id;
            return account;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsEnable
        {
            get
            {
                return _IsEnable;
            }
            set
            {
                OnIsEnableChanging(value);
                ReportPropertyChanging("IsEnable");
                _IsEnable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnable");
                OnIsEnableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsEnable;
        partial void OnIsEnableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsEnableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CanUploadData
        {
            get
            {
                return _CanUploadData;
            }
            set
            {
                OnCanUploadDataChanging(value);
                ReportPropertyChanging("CanUploadData");
                _CanUploadData = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanUploadData");
                OnCanUploadDataChanged();
            }
        }
        private Nullable<global::System.Boolean> _CanUploadData;
        partial void OnCanUploadDataChanging(Nullable<global::System.Boolean> value);
        partial void OnCanUploadDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoringSystemModel", Name="MailAddressReceiveMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MailAddressReceiveMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MailAddressReceiveMessage object.
        /// </summary>
        /// <param name="mailAddress">Initial value of the MailAddress property.</param>
        public static MailAddressReceiveMessage CreateMailAddressReceiveMessage(global::System.String mailAddress)
        {
            MailAddressReceiveMessage mailAddressReceiveMessage = new MailAddressReceiveMessage();
            mailAddressReceiveMessage.MailAddress = mailAddress;
            return mailAddressReceiveMessage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MailAddress
        {
            get
            {
                return _MailAddress;
            }
            set
            {
                if (_MailAddress != value)
                {
                    OnMailAddressChanging(value);
                    ReportPropertyChanging("MailAddress");
                    _MailAddress = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MailAddress");
                    OnMailAddressChanged();
                }
            }
        }
        private global::System.String _MailAddress;
        partial void OnMailAddressChanging(global::System.String value);
        partial void OnMailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsEnable
        {
            get
            {
                return _IsEnable;
            }
            set
            {
                OnIsEnableChanging(value);
                ReportPropertyChanging("IsEnable");
                _IsEnable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnable");
                OnIsEnableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsEnable;
        partial void OnIsEnableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsEnableChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoringSystemModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Order CreateOrder(global::System.Int32 id)
        {
            Order order = new Order();
            order.Id = id;
            return order;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductNo
        {
            get
            {
                return _ProductNo;
            }
            set
            {
                OnProductNoChanging(value);
                ReportPropertyChanging("ProductNo");
                _ProductNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductNo");
                OnProductNoChanged();
            }
        }
        private global::System.String _ProductNo;
        partial void OnProductNoChanging(global::System.String value);
        partial void OnProductNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OuterCode
        {
            get
            {
                return _OuterCode;
            }
            set
            {
                OnOuterCodeChanging(value);
                ReportPropertyChanging("OuterCode");
                _OuterCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OuterCode");
                OnOuterCodeChanged();
            }
        }
        private global::System.String _OuterCode;
        partial void OnOuterCodeChanging(global::System.String value);
        partial void OnOuterCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArticleNo
        {
            get
            {
                return _ArticleNo;
            }
            set
            {
                OnArticleNoChanging(value);
                ReportPropertyChanging("ArticleNo");
                _ArticleNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArticleNo");
                OnArticleNoChanged();
            }
        }
        private global::System.String _ArticleNo;
        partial void OnArticleNoChanging(global::System.String value);
        partial void OnArticleNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShoeName
        {
            get
            {
                return _ShoeName;
            }
            set
            {
                OnShoeNameChanging(value);
                ReportPropertyChanging("ShoeName");
                _ShoeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShoeName");
                OnShoeNameChanged();
            }
        }
        private global::System.String _ShoeName;
        partial void OnShoeNameChanging(global::System.String value);
        partial void OnShoeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliveryCountry
        {
            get
            {
                return _DeliveryCountry;
            }
            set
            {
                OnDeliveryCountryChanging(value);
                ReportPropertyChanging("DeliveryCountry");
                _DeliveryCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliveryCountry");
                OnDeliveryCountryChanged();
            }
        }
        private global::System.String _DeliveryCountry;
        partial void OnDeliveryCountryChanging(global::System.String value);
        partial void OnDeliveryCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.String _Size;
        partial void OnSizeChanging(global::System.String value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CSDDate
        {
            get
            {
                return _CSDDate;
            }
            set
            {
                OnCSDDateChanging(value);
                ReportPropertyChanging("CSDDate");
                _CSDDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CSDDate");
                OnCSDDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CSDDate;
        partial void OnCSDDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCSDDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedTime
        {
            get
            {
                return _CreatedTime;
            }
            set
            {
                OnCreatedTimeChanging(value);
                ReportPropertyChanging("CreatedTime");
                _CreatedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedTime");
                OnCreatedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedTime;
        partial void OnCreatedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedTime
        {
            get
            {
                return _UpdatedTime;
            }
            set
            {
                OnUpdatedTimeChanging(value);
                ReportPropertyChanging("UpdatedTime");
                _UpdatedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedTime");
                OnUpdatedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedTime;
        partial void OnUpdatedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoringSystemModel", Name="Storing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Storing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Storing object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Storing CreateStoring(global::System.Int32 id)
        {
            Storing storing = new Storing();
            storing.Id = id;
            return storing;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductNo
        {
            get
            {
                return _ProductNo;
            }
            set
            {
                OnProductNoChanging(value);
                ReportPropertyChanging("ProductNo");
                _ProductNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductNo");
                OnProductNoChanged();
            }
        }
        private global::System.String _ProductNo;
        partial void OnProductNoChanging(global::System.String value);
        partial void OnProductNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OuterCode
        {
            get
            {
                return _OuterCode;
            }
            set
            {
                OnOuterCodeChanging(value);
                ReportPropertyChanging("OuterCode");
                _OuterCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OuterCode");
                OnOuterCodeChanged();
            }
        }
        private global::System.String _OuterCode;
        partial void OnOuterCodeChanging(global::System.String value);
        partial void OnOuterCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Barcode
        {
            get
            {
                return _Barcode;
            }
            set
            {
                OnBarcodeChanging(value);
                ReportPropertyChanging("Barcode");
                _Barcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Barcode");
                OnBarcodeChanged();
            }
        }
        private global::System.String _Barcode;
        partial void OnBarcodeChanging(global::System.String value);
        partial void OnBarcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CompleteCarton
        {
            get
            {
                return _CompleteCarton;
            }
            set
            {
                OnCompleteCartonChanging(value);
                ReportPropertyChanging("CompleteCarton");
                _CompleteCarton = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompleteCarton");
                OnCompleteCartonChanged();
            }
        }
        private Nullable<global::System.Boolean> _CompleteCarton;
        partial void OnCompleteCartonChanging(Nullable<global::System.Boolean> value);
        partial void OnCompleteCartonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SizeNo
        {
            get
            {
                return _SizeNo;
            }
            set
            {
                OnSizeNoChanging(value);
                ReportPropertyChanging("SizeNo");
                _SizeNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SizeNo");
                OnSizeNoChanged();
            }
        }
        private global::System.String _SizeNo;
        partial void OnSizeNoChanging(global::System.String value);
        partial void OnSizeNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CartonNo
        {
            get
            {
                return _CartonNo;
            }
            set
            {
                OnCartonNoChanging(value);
                ReportPropertyChanging("CartonNo");
                _CartonNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CartonNo");
                OnCartonNoChanged();
            }
        }
        private Nullable<global::System.Int32> _CartonNo;
        partial void OnCartonNoChanging(Nullable<global::System.Int32> value);
        partial void OnCartonNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> GrossWeight
        {
            get
            {
                return _GrossWeight;
            }
            set
            {
                OnGrossWeightChanging(value);
                ReportPropertyChanging("GrossWeight");
                _GrossWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GrossWeight");
                OnGrossWeightChanged();
            }
        }
        private Nullable<global::System.Double> _GrossWeight;
        partial void OnGrossWeightChanging(Nullable<global::System.Double> value);
        partial void OnGrossWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ActualWeight
        {
            get
            {
                return _ActualWeight;
            }
            set
            {
                OnActualWeightChanging(value);
                ReportPropertyChanging("ActualWeight");
                _ActualWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActualWeight");
                OnActualWeightChanged();
            }
        }
        private Nullable<global::System.Double> _ActualWeight;
        partial void OnActualWeightChanging(Nullable<global::System.Double> value);
        partial void OnActualWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DifferencePercent
        {
            get
            {
                return _DifferencePercent;
            }
            set
            {
                OnDifferencePercentChanging(value);
                ReportPropertyChanging("DifferencePercent");
                _DifferencePercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DifferencePercent");
                OnDifferencePercentChanged();
            }
        }
        private Nullable<global::System.Double> _DifferencePercent;
        partial void OnDifferencePercentChanging(Nullable<global::System.Double> value);
        partial void OnDifferencePercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsPass
        {
            get
            {
                return _IsPass;
            }
            set
            {
                OnIsPassChanging(value);
                ReportPropertyChanging("IsPass");
                _IsPass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPass");
                OnIsPassChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsPass;
        partial void OnIsPassChanging(Nullable<global::System.Boolean> value);
        partial void OnIsPassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsFirstPass
        {
            get
            {
                return _IsFirstPass;
            }
            set
            {
                OnIsFirstPassChanging(value);
                ReportPropertyChanging("IsFirstPass");
                _IsFirstPass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFirstPass");
                OnIsFirstPassChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsFirstPass;
        partial void OnIsFirstPassChanging(Nullable<global::System.Boolean> value);
        partial void OnIsFirstPassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedAccount
        {
            get
            {
                return _CreatedAccount;
            }
            set
            {
                OnCreatedAccountChanging(value);
                ReportPropertyChanging("CreatedAccount");
                _CreatedAccount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedAccount");
                OnCreatedAccountChanged();
            }
        }
        private global::System.String _CreatedAccount;
        partial void OnCreatedAccountChanging(global::System.String value);
        partial void OnCreatedAccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedTime
        {
            get
            {
                return _CreatedTime;
            }
            set
            {
                OnCreatedTimeChanging(value);
                ReportPropertyChanging("CreatedTime");
                _CreatedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedTime");
                OnCreatedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedTime;
        partial void OnCreatedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedTime
        {
            get
            {
                return _UpdatedTime;
            }
            set
            {
                OnUpdatedTimeChanging(value);
                ReportPropertyChanging("UpdatedTime");
                _UpdatedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedTime");
                OnUpdatedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedTime;
        partial void OnUpdatedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedTimeChanged();

        #endregion

    
    }

    #endregion

    
}
